### ISSUE TITLE
BMP images not loading

### ISSUE THREAD

**Issue by casidiablo** [paperdink/timcal#3]
I get: `bitmap format not handled.` in the logs. Some println debbing tells me that the bitmaps header do not match at runtime:

```
  // Parse BMP header
  uint16_t header = read16(file);
  DEBUG.print("header: ");
  DEBUG.println(header);
  DEBUG.println(0x4D42);
  if (header == 0x4D42) // BMP signature
  {
```

This prints:

```
05:40:13.806 -> header: 65535
05:40:13.806 -> 19778
```

Where 19778 is decimal for 0x4D42.

`hexdump` tells me the BMP files have the right header. Also `65535` is a bit suspicious.

Also, unrelated: what do I provide as timezone during the config phase. I tried PST but it keeps showing the hour in UTC, and the days in the calendar do not show up.

**Comment by treo** [comment]
I ran into exactly the same problem. 

You need to upload the files in `/data` in addition to uploading the sketch itself. 

To upload it follow the tutorial linked here, to first install the upload tool into the Arduino IDE: https://randomnerdtutorials.com/install-esp32-filesystem-uploader-arduino-ide/

Then you'll have to go to "Tools -> ESP32 Sketch Data Upload":
![image](https://user-images.githubusercontent.com/509379/170864674-9bf4ced4-7e09-4e3e-87a9-85f5055e7a26.png)

Note: That will also wipe out your previously saved config. 

For the offset, it looks like it will set a `TZ` environment variable to `UTC` + whatever you provide. 

In principle that means you should be setting it to your UTC offset. But for whatever reason, it does the offsetting backwards in my case, i.e. to get UTC+2 I had to actually set the value to UTC-2. 

In order to get the days to be displayed, I had to change the START_DAY_OFFSET to 1 and also update CAL_STRING to start with Sun in `config.h`:
```
#define START_DAY_OFFSET 1
#define CAL_STRING "Sun   Mon   Tue   Wed   Thu   Fri   Sat"
```

**Comment by rgujju** [comment]
The latest commit should fix the problem with CAL_STRING. 
Additionally we have added the ESP32 sketch data upload to README and a new example [Timcal2](https://github.com/paperdink/timcal2) for those who prefer editing config files.
